version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install serverless -g
  build:
    commands:
      - cp .serverless/.serverless-staging/* .serverless/
      - export subdomain="staging"; export stage="staging"; serverless --stage="staging"  
      - cp .serverless/* .serverless/.serverless-staging
  post_build:
    commands: 
      - aws s3 sync ./.serverless s3://credmark-staging-website/.serverless-staging;
