import Head from 'next/head'
import Nav from '../components/layout/nav'
import Whitepaper from '../components/pages/whitepaper'

export default function WhitepaperPage() {
  return (
    <>
      <Head>
        <title>CREDMARK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Nav
          page={<Whitepaper />} />
      </div>
    </>
  )
}